# Follow a transform with the endpoint of a robot arm

################## GOAL ####################
string frame_id                             # Name of the transform we want to track
float64 position_tolerance 0.1              # Maximum permissable error on position error (m)
float64 orientation_tolerance 0.5           # Maximum permissable error on orienation (rad)
float64 timeout 0.5                         # Time to wait for transform to appear
---
################ RESULT ####################
Statistics position_error                   # Norm of difference between desired and actual (m)
Statistics orientation_error                # Angle from the Lie algebra of quaternion (rad)
string message                              # Human-readable
---
################ FEEDBACK ##################
std_msgs/Header header                      # Contains time stamp
float64 position_error                      # Norm of difference between desired and actual (m)
float64 orientation_error                   # Angle from the Lie algebra of quaternion (rad)
float64 manipulability                      # Proximity to a singularity (0 = singular)
