# Follow a tf2 transform object with the robot endpoint

################## GOAL ####################
geometry_msgs/TransformStamped transform    # What to follow
float64 position_tolerance 0.05             # Maximum permissable error on position error (m)
float64 orientation_error 0.5               # Maximum permissable error on orienation (rad)
float64 timeout 5.0                         # Time to wait for transform to appear
---
################ RESULT ####################
Statistics position_error                   # Contains information on mean, variance, min, max
Statistics orientation_error                # Contains information on mean, variance, min, max
string message                              # Information for the client
---
################ FEEDBACK ##################
std_msgs/Header header                      # Time of publication, reference frame
CartesianState actual                       # Computed value from the forward kinematics
CartesianState desired                      # Value from the trajectory
