# Hold a given pose with the endpoint of a robot arm

################## GOAL ####################
geometry_msgs/PoseStamped pose              # The pose to maintain
float64 position_tolerance 0.1              # Maximum permissable error on position error (m)
float64 orientation_tolerance 0.5           # Maximum permissable error on orienation (rad)
---
################ RESULT ####################
Statistics position_error                   # Contains information on mean, variance, min, max
Statistics orientation_error                # Contains information on mean, variance, min, max
string message                              # Information for the client
---
################ FEEDBACK ##################
std_msgs/Header header                      # Time of publication, reference frame
CartesianState actual                       # Actual pose, velocity computed from forward kinematics
CartesianState desired                      # Desired pose, velocity, acceleration
float64 manipulability                      # Proximity to a singularity
