# Goal
geometry_msgs::Transform desired_pose
float54 time_from_start
---
# Result
float64 final_position_error
float64 final_orientation_error
---
# Feedback
float64 position_tracking_error
float64 orientation_tracking_error
float64 time_to_completion
float64 manipulability
