# Goal
float64 duration
geometry_msgs::Transform pose
---
# Result
float64 position_error_mean
float64 position_error_variance
---
# Feedback
float64 position_error
float64 orientation_error
float64 time_to_completion
float64 manipulability
